Resources:
    NewEC2:
        Type: AWS::EC2::Instance
        Properties: 
            AvailabilityZone:
                Fn::Select: 
                    - 0
                    - Fn::GetAZs: "us-west-2"
            DisableApiTermination: "false"
            ImageId: "ami-0ac73f33a1888c64a" #"ami-0800fc0fa715fdcfe"
            BlockDeviceMappings: 
                    -   DeviceName: "/dev/xvda"
                        Ebs:
                            VolumeSize: 30
                            DeleteOnTermination: "true"
                            VolumeType: "gp2"
            InstanceType: "t2.large"
            KeyName: "udacity"
            NetworkInterfaces: 
                -   AssociatePublicIpAddress: "true"
                    DeleteOnTermination: "true"
                    DeviceIndex: "0"
                    GroupSet: 
                        - !ImportValue P5Stack-EC2SecGroup
                    SubnetId:   !ImportValue P5Stack-PublicSubnet1
            UserData:   # User data
                    Fn::Base64: !Sub |
                        #!/bin/bash
                        wget -P /home/ubuntu/ https://github.com/MohamedElAzhary/FinalProject/archive/refs/heads/master.zip
                        cd /home/ubuntu/
                        apt-get install unzip make -y
                        unzip -o master.zip
                        cd /home/ubuntu/FinalProject-master
                        bash installBase.sh
                        apt-get update && apt-get install docker.io -y
                        systemctl start docker
                        su ubuntu bash -c "bash /home/ubuntu/FinalProject-master/installDocker.sh";

            Tags: 
                -   Key: "Name"
                    Value: "Green"


Outputs:
    EC2ID:
        Description: EC2 ID of Instance
        Value: 
            !Ref NewEC2
        Export:
            Name: !Sub "${AWS::StackName}-EC2ID"

    EC2PRIVIP:
        Description: EC2 PRIV IP of Instance
        Value: 
            !GetAtt NewEC2.PrivateIp
        Export:
            Name: !Sub "${AWS::StackName}-EC2PRIVIP"
    
    EC2PUBIP:
        Description: EC2 PUB IP of Instance
        Value: 
            !GetAtt NewEC2.PublicIp
        Export:
            Name: !Sub "${AWS::StackName}-EC2PUBIP"