version: 2.1
orbs:
  docker: circleci/docker@1.6.0
  
jobs:
    lint:
        docker:
            - image: httpd:2.4
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: lint
                command: |
                    apt-get update && apt-get install make unzip awscli wget -y && make installBase && make lint
    buildandpush:
        executor: docker/docker
        steps:
          - setup_remote_docker
          - checkout
          - docker/check
          - docker/build:
              image: moazario/siteimage
          - docker/push:
              digest-path: /tmp/digest.txt
              image: moazario/siteimage
          - run:
              command: |
                echo "Digest is: $(</tmp/digest.txt)"


    deploy:
        docker:
            - image: httpd:2.4
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: deploy
                no_output_timeout: 20m
                working_directory: ~/repo
                command: |
                    apt-get update && apt-get install make unzip awscli wget -y && make installBase && bash bluegreen.sh
            
            
workflows:
  prod-deployment:
    jobs:
      - lint
      - buildandpush:
            requires: [lint]
      - deploy:
            requires: [buildandpush]
