version: 2.1
jobs:
    lint:
        docker:
            - image: httpd:2.4
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: install dependencies
                command: |
                    apt-get update && apt-get install make unzip awscli wget -y && make lint
            

    deploy:
        docker:
            - image: httpd:2.4
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: install dependencies
                working_directory: ~/repo
                command: |
                    apt-get update && apt-get install make unzip awscli wget -y && bash bluegreen
            
            
workflows:
  prod-deployment:
    jobs:
      - lint
      - deploy
