version: 2
jobs:
    build:
        docker:
            # Use the same Docker base as the project
            - image: httpd:2.4 #python:3.7.3-stretch

        working_directory: ~/repo
        steps:
            -   checkout
            # Download and cache dependencies
            ##-   restore_cache:
                    ##keys:
                        #- v1-dependencies-{{ checksum "README.md" }}
                        # fallback to using the latest cache if no exact match is found
                        #- v1-dependencies-
            -   run:
                    name: install dependencies
                    command: |
                        apt-get update && apt-get install make unzip awscli wget -y && make installBase
            -   save_cache:
                    paths:
                        -   ~/repo
                    key: v1-dependencies-{{ checksum "README.md" }}
                
            # run lint!
            -   run:
                    name: run lint
                    command: |
                        make lint 
    deploy:
        docker:
        # Use the same Docker base as the project
            - image: httpd:2.4 #python:3.7.3-stretch

        working_directory: ~/repo
        steps:
            -   checkout

            -   restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "README.md" }}
                    

            -   run:
                name: run lint
                command: |
                    apt-get update && apt-get install make unzip awscli -y
                    bash bluegreen.sh 