version: 2.1
orbs:
  docker: circleci/docker@1.6.0
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0

jobs:
    lint:
        docker:
            - image: httpd:2.4
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: lint
                command: |
                    apt-get update && apt-get install make unzip awscli wget -y && make installBase && make lint
    buildandpush:
        executor: docker/docker
        steps:
          - setup_remote_docker
          - checkout
          - docker/check
          - docker/build:
              image: moazario/siteimage
              tag: 'siteimage'
          - docker/push:
              digest-path: /tmp/digest.txt
              image: moazario/siteimage
              tag: 'siteimage'
          - run:
              command: |
                echo "Digest is: $(</tmp/digest.txt)"

    deployInfrastructure:
        docker:
            - image: httpd:2.4
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: deployInfra
                no_output_timeout: 20m
                working_directory: ~/repo
                command: |
                  bash create_infra.sh
                  echo "Infrastructure has been created"


    deployEC2:
        docker:
            - image: httpd:2.4
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: deployEC2
                no_output_timeout: 20m
                working_directory: ~/repo
                command: |
                    apt-get update && apt-get install make unzip awscli wget -y && make installBase && bash bluegreen.sh

          
workflows:
  prod-deployment:
    jobs:
      - deployInfrastructure
      - lint
      - buildandpush:
            requires: [lint]
      - deployEC2:
            requires: [buildandpush]
