version: 2.1
jobs:
    lint:
        docker:
            - image: httpd:2.4
        steps:
            - checkout
            - run:
                name: install dependencies
                working_directory: ./repo
                command: |
                    apt-get update && apt-get install make unzip awscli wget -y && make lint
            - persist_to_workspace:
                root: .
                paths:
                    -  /repo

    deploy:
        docker:
            - image: httpd:2.4
        steps:
            - checkout
            -   attach_workspace:
                    at: ./repo
            - run:
                name: install dependencies
                working_directory: ./repo
                command: |
                    apt-get update && apt-get install make unzip awscli wget -y && bash bluegreen
            - persist_to_workspace:
                root: .
                paths:
                    -  /repo

workflows:
  prod-deployment:
    jobs:
      - lint
      - deploy
