version: 2.1
jobs:
    lint:
        docker:
            - image: httpd:2.4
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: lint
                command: |
                    apt-get update && apt-get install make unzip awscli wget -y && make installBase && make lint
            

    deploy:
        docker:
            - image: httpd:2.4
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: deploy
                working_directory: ~/repo
                command: |
                    apt-get update && apt-get install make unzip awscli wget -y && make installBase && bash bluegreen.sh
            
            
workflows:
  prod-deployment:
    jobs:
      - lint
      - deploy
        requires: [lint]
